"""Add 'deadlines_type' to Course

Revision ID: 2226e9ac60f3
Revises: b7ada3a48dea
Create Date: 2025-09-01 11:19:01.773016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2226e9ac60f3'
down_revision: Union[str, None] = 'b7ada3a48dea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('deadlines_type', sa.Enum('HARD', 'INTERPOLATE', name='deadlines_type', native_enum=False), server_default='HARD', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'deadlines_type')
    # ### end Alembic commands ###
