"""Add RMS ID into database

Revision ID: 322d380606c2
Revises: 428bcd9f5db6
Create Date: 2025-07-31 16:02:07.404461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '322d380606c2'
down_revision: Union[str, None] = '428bcd9f5db6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rms_id', sa.Integer()))
    op.create_unique_constraint(op.f('uq_users_rms_id'), 'users', ['rms_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_rms_id'), 'users', type_='unique')
    op.drop_column('users', 'rms_id')
    # ### end Alembic commands ###
