"""add_final_grade_fields_to_user_on_course

Revision ID: 725a697ec7b9
Revises: e3734758a52e
Create Date: 2025-12-18 13:06:30.555989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '725a697ec7b9'
down_revision: Union[str, None] = 'e3734758a52e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_on_courses', sa.Column('final_grade', sa.Integer(), nullable=True))
    op.add_column('users_on_courses', sa.Column('final_grade_override', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_on_courses', 'final_grade_override')
    op.drop_column('users_on_courses', 'final_grade')
    # ### end Alembic commands ###
