"""add_comment_to_user_on_course

Revision ID: 8a711d509af1
Revises: 2226e9ac60f3
Create Date: 2025-09-29 13:15:59.785824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a711d509af1'
down_revision: Union[str, None] = '2226e9ac60f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_on_courses', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_on_courses', 'comment')
    # ### end Alembic commands ###
