"""Add url to Task

Revision ID: b4b7a8a28ac0
Revises: 037c4373e638
Create Date: 2025-03-07 07:30:04.532245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4b7a8a28ac0'
down_revision: Union[str, None] = '037c4373e638'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'url')
    # ### end Alembic commands ###
