"""add extra statuses for course model

Revision ID: b7ada3a48dea
Revises: 54669924eda0
Create Date: 2025-08-24 01:24:18.156045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7ada3a48dea'
down_revision: Union[str, None] = '54669924eda0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('status', sa.Enum('CREATED', 'HIDDEN', 'IN_PROGRESS', 'ALL_TASKS_ISSUED', 'DORESHKA', 'FINISHED', name='course_status', native_enum=False), server_default='CREATED', nullable=False))
    op.drop_column('courses', 'is_ready')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('is_ready', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('courses', 'status')
    # ### end Alembic commands ###
