"""Add positions to Task and TaskGroup

Revision ID: c3c1bd781e0f
Revises: b4b7a8a28ac0
Create Date: 2025-03-14 05:33:12.266981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3c1bd781e0f'
down_revision: Union[str, None] = 'b4b7a8a28ac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_groups', sa.Column('position', sa.Integer(), server_default='0', nullable=False))
    op.add_column('tasks', sa.Column('position', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'position')
    op.drop_column('task_groups', 'position')
    # ### end Alembic commands ###
