name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'

change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'


autolabeler:
  - label: 'type: feature'
    title:
      - '/feat:.*/'
      - '/feature:.*/'
  - label: 'type: fix'
    branch:
      - '/fix.+/'
      - '/bug.+/'
    title:
      - '/fix:.*/'
      - '/bugfix:.*/'
      - '/bug:.*/'
  - label: 'type: chore'
    files:
      - '*.md'
      - '*.txt'
  - label: 'type: docs'
    branch:
      - '/docs.+/'
    title:
      - '/docs:.*/'
  - label: 'type: refactor'
    title:
      - '/ref:.*/'
      - '/refactor:.*/'
  - label: 'type: style'
    title:
      - '/style:.*/'
  - label: 'type: performance'
    title:
      - '/perf:.*/'
      - '/performance:.*/'
  - label: 'type: test'
    title:
      - '/test:.*/'
      - '/tests:.*/'
    files:
      - 'tests/*'
  - label: 'type: ci'
    title:
      - '/ci:.*/'
    files:
      - '.github/*'


categories:
  - title: 'Breaking'
    label: 'type: breaking'
  - title: 'Features'
    label: 'type: feature'
  - title: 'Fixes'
    label: 'type: fix'
  - title: 'Documentation'
    label: 'type: docs'
  - title: 'CI/CD'
    labels:
      - 'type: test'
      - 'type: ci'
  - title: 'Enhancement'
    labels:
      - 'type: refactor'
      - 'type: performance'
      - 'type: style'
  - title: 'Other changes'

version-resolver:
  major:
    labels:
      - 'type: breaking'
  minor:
    labels:
      - 'type: feature'
  default: patch

template: |
  $CHANGES
    
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION
