name: python

# course
deadlines: hard
second_deadline_max: 0.4
low_demand_bonus_bound: 0.4
max_low_demand_bonus: 1.2


# checker (useless for manytask, important for checker)
system: python
layout: groups
executor: sandbox
templates: create


# gitlab
gitlab_url: https://gitlab.manytask.org
default_branch: main
course_group: python
public_repo: python/public-2022-fall
students_group: python/students-fall-2022
#lectures_repo: py-tasks/lectures-2022-spring

# manytask
manytask_url: https://py.manytask.org


# info
lms_url: https://lk.yandexdataschool.ru/
telegram_channel_invite: https://t.me/joinchat/
telegram_chat_invite: https://t.me/joinchat/
