- group: group_7
  start: 01-03-2040 18:00
  deadline: 01-04-2040 23:59
  second_deadline: 01-05-2040 23:59
  enabled: true
  tasks:
    - task: task_7_0
      score: 70

- group: group_6
  start: 01-05-2020 18:00
  deadline: 01-06-2020 23:59
  second_deadline: 01-01-2040 23:59
  enabled: true
  tasks:
    - task: task_6_0
      score: 60
      url: https://www.python.org/about/gettingstarted/
    - task: task_6_1
      score: 60

- group: group_5
  start: 01-05-2020 18:00
  deadline: 01-01-2040 23:59
  second_deadline: 01-01-2040 23:59
  enabled: true
  tasks:
    - task: task_5_0
      score: 50
    - task: task_5_1
      score: 50
    - task: task_5_2
      score: 50

- group: group_4
  special: true
  start: 01-03-2020 18:00
  deadline: 01-04-2020 23:59
  second_deadline: 01-05-2020 23:59
  enabled: true
  tasks:
    - task: task_4_0
      score: 40
    - task: task_4_1
      score: 40
    - task: task_4_2
      score: 40

- group: group_3
  start: 01-03-2020 18:00
  deadline: 01-04-2020 23:59
  second_deadline: 01-05-2020 23:59
  enabled: true
  tasks:
    - task: task_3_0
      score: 30
    - task: task_3_1
      score: 30
    - task: task_3_2
      score: 30
    - task: task_3_3
      score: 30

- group: group_2
  start: 01-02-2020 18:00
  deadline: 01-03-2020 23:59
  tasks:
    - task: task_2_0
      score: 20
    - task: task_2_1
      score: 20
    - task: task_2_2
      score: 20
    - task: task_2_3
      score: 20

- group: group_1
  start: 01-01-2020 18:00
  deadline: 01-02-2020 23:59
  second_deadline: 01-02-2020 23:59
  enabled: true
  tasks:
    - task: task_1_0
      score: 10
    - task: task_1_1
      score: 10
    - task: task_1_2
      score: 10
    - task: task_1_3
      score: 10
    - task: task_1_4
      score: 10

- group: group_0
  start: 01-01-2000 18:00
  deadline: 01-02-2000 23:59
  second_deadline: 01-02-2000 23:59
  enabled: true
  tasks:
    - task: task_0_0
      score: 10
    - task: task_0_1
      score: 10
    - task: task_0_2
      score: 10
    - task: task_0_3
      score: 10
    - task: task_0_4
      score: 10
    - task: task_0_5
      score: 10
