version: 1


settings:  # required
  course_name: python

  gitlab_base_url: https://gitlab.manytask.org
  public_repo: python/public-2022-fall
  students_group: python/students-fall-2022


ui:
  task_url_template: https://gitlab.manytask.org/test/$GROUP_NAME/$TASK_NAME

  # optional, any number of links
  links:
    "TG Channel": https://t.me/joinchat/
    "TG Chat": https://t.me/joinchat/
    "LMS": https://lk.yandexdataschool.ru/
    "Contribute Manytask": https://github.com/manytask


deadlines:
  timezone: Europe/Moscow

  deadlines: hard  # hard/interpolate
  max_submissions: 10  # optional
  submission_penalty: 0.1  # optional

  schedule:
    - group: group_7
      start: 2040-03-01 18:00
      steps:
        0.5: 2040-04-01 23:59
      end: 2040-05-01 23:59
      enabled: true
      tasks:
        - task: task_7_0
          score: 70

    - group: group_6
      start: 2020-05-01 18:00
      steps:
        0.5: 2020-06-01 23:59
        0.3: 2040-05-01 23:59
      end: 2040-08-01 23:59
      enabled: true
      tasks:
        - task: task_6_0
          score: 60
          url: https://www.python.org/about/gettingstarted/
        - task: task_6_1
          score: 60

    - group: group_5
      start: 2020-05-01 18:00
      steps:
        0.5: 2040-01-01 23:59
      end: 2040-02-01 23:59
      enabled: true
      tasks:
        - task: task_5_0
          score: 50
        - task: task_5_1
          score: 50
        - task: task_5_2
          score: 50

    - group: group_4
      special: true
      start: 2020-03-01 18:00
      steps:
        0.5: 2020-04-01 23:59
      end: 2040-05-01 23:59
      enabled: true
      tasks:
        - task: task_4_0
          score: 40
        - task: task_4_1
          score: 40
        - task: task_4_2
          score: 40

    - group: group_3
      start: 2020-03-01 18:00
      steps:
        0.5: 2020-03-01 23:59
      end: 2020-05-01 23:59
      enabled: true
      tasks:
        - task: task_3_0
          score: 30
        - task: task_3_1
          score: 30
        - task: task_3_2
          score: 30
        - task: task_3_3
          score: 30

    - group: group_2
      start: 2000-02-01 18:00
      end: 2000-03-01 23:59
      tasks:
        - task: task_2_0
          score: 20
        - task: task_2_1
          score: 20
        - task: task_2_2
          score: 20
        - task: task_2_3
          score: 20

    - group: group_1
      start: 2000-01-01 18:00
      steps:
        0.5: 2000-02-01 23:59
      end: 2000-02-01 23:59
      enabled: true
      tasks:
        - task: task_1_0
          score: 10
        - task: task_1_1
          score: 10
        - task: task_1_2
          score: 10
        - task: task_1_3
          score: 10
        - task: task_1_4
          score: 10

    - group: group_0
      start: 2000-01-01 18:00
      steps:
        0.5: 2000-03-01 18:00
      end: 2000-05-01 23:59
      enabled: true
      tasks:
        - task: task_0_0
          score: 10
        - task: task_0_1
          score: 10
        - task: task_0_2
          score: 10
        - task: task_0_3
          score: 10
        - task: task_0_4
          score: 10
        - task: task_0_5
          score: 10
