exclude: ^manytask/migrations/versions

repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.1.0
    hooks:
      - name: Check semantic commit message
        id: conventional-pre-commit
        stages: [commit-msg]
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check --fix
        language: system
        types: [python]
        pass_filenames: true
      - id: ruff-format
        name: ruff format
        entry: ruff format
        language: system
        types: [python]
        pass_filenames: true
