repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.1.0
    hooks:
      - name: Check semantic commit message
        id: conventional-pre-commit
        stages: [commit-msg]
  - repo: local
    hooks:
      - id: check-staged
        name: Check staged files
        entry: scripts/check_staged.sh
        language: script
        pass_filenames: false
        verbose: true
        types: [python]
