version: "3.8"


services:
    manytask:
        environment:
            FLASK_ENV: development
        ports:
            - "5000:5000"
        volumes:
            - ./manytask/:/app/manytask
            - .tmp/cache/:/cache
            - .tmp/solutions/:/solutions
