networks:
  manytask-net:
    external: true
    name: nginx-manytask-net
  postgres-net-src:
    name: postgres-net-src
    driver: bridge

volumes:
    cache-src:
    solutions-src:
    postgres_data_src:
        name: manytask_postgres_data_src

services:
    docs:
        build:
            dockerfile: Dockerfile
            context: .
            target: docs
        container_name: manytask-docs-src
        restart: always
        expose:
            - "80"
        environment:
            VIRTUAL_HOST: docs-src.manytask2.org
            VIRTUAL_PORT: 80
            LETSENCRYPT_HOST: docs-src.manytask2.org
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:80" ]
            interval: 1m
            timeout: 15s
            retries: 3
            start_period: 30s
        networks:
            - manytask-net
    manytask:
        # image: manytask/manytask:latest  # set SPECIFIC version you'll use
        build:
            dockerfile: Dockerfile
            context: .
            target: app
        container_name: manytask-src
        restart: always
        expose:
            - "5050"
        env_file: .env.src
        environment:
            VIRTUAL_HOST: src.manytask2.org
            VIRTUAL_PORT: 5050
            LETSENCRYPT_HOST: src.manytask2.org
            LETSENCRYPT_EMAIL: no-reply@manytask.org
        volumes:
            - cache-src:/cache
        depends_on:
            postgres:
                condition: service_healthy
        links:
            -   postgres:postgres
        networks:
            - manytask-net
            - postgres-net-src
    postgres:
        image: postgres:17
        container_name: manytask_postgres_src
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: manytask
        ports:
            - "5433:5432"
        volumes:
            - postgres_data_src:/var/lib/postgresql/data
        networks:
            - postgres-net-src
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d manytask"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s
