services:
  web:
    image: manytask-docs
    container_name: manytask-docs
    restart: always
    network_mode: bridge
    expose:
      - "8080"
    environment:
      VIRTUAL_HOST: manytask2.org
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: manytask2.org
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5050/healthcheck" ]
      interval: 1m
      timeout: 15s
      retries: 3
      start_period: 30s

