TEST_USERNAME = "username"
TEST_FIRST_NAME = "First"
TEST_LAST_NAME = "Last"
TEST_RMS_ID = 123

TEST_USERNAME_1 = "user1"
TEST_FIRST_NAME_1 = "First"
TEST_LAST_NAME_1 = "Last1"
TEST_RMS_ID_1 = 123
TEST_USERNAME_2 = "user2"
TEST_FIRST_NAME_2 = "First2"
TEST_LAST_NAME_2 = "Last2"
TEST_REPO_NAME_2 = "repo2"
TEST_RMS_ID_2 = 456
TEST_USERNAME_3 = "user3"
TEST_FIRST_NAME_3 = "First3"
TEST_LAST_NAME_3 = "Last3"
TEST_REPO_NAME_3 = "repo3"
