"""Add gitlab and ui params to Course

Revision ID: 0ec2a815ec09
Revises: b4b7a8a28ac0
Create Date: 2025-03-28 04:31:51.707607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import manytask


# revision identifiers, used by Alembic.
revision: str = '0ec2a815ec09'
down_revision: Union[str, None] = 'b4b7a8a28ac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('gitlab_course_group', sa.String(), nullable=False))
    op.add_column('courses', sa.Column('gitlab_course_public_repo', sa.String(), nullable=False))
    op.add_column('courses', sa.Column('gitlab_course_students_group', sa.String(), nullable=False))
    op.add_column('courses', sa.Column('gitlab_default_branch', sa.String(), nullable=False))
    op.add_column('courses', sa.Column('task_url_template', sa.String(), nullable=False))
    op.add_column('courses', sa.Column('links', manytask.models.StrStrDict(), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'links')
    op.drop_column('courses', 'task_url_template')
    op.drop_column('courses', 'gitlab_default_branch')
    op.drop_column('courses', 'gitlab_course_students_group')
    op.drop_column('courses', 'gitlab_course_public_repo')
    op.drop_column('courses', 'gitlab_course_group')
    # ### end Alembic commands ###
