"""Add enabled flag to Task model

Revision ID: 1e324171ec8b
Revises: a7c68744b7a5
Create Date: 2025-03-04 06:05:19.004916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e324171ec8b'
down_revision: Union[str, None] = 'a7c68744b7a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('enabled', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'enabled')
    # ### end Alembic commands ###
