"""Add role admin to User model

Revision ID: 428bcd9f5db6
Revises: d8b7ebab0173
Create Date: 2025-07-20 16:02:41.616794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '428bcd9f5db6'
down_revision: Union[str, None] = 'd8b7ebab0173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_instance_admin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_instance_admin')
    # ### end Alembic commands ###
