"""Add token to course

Revision ID: 460f79c9733b
Revises: a7c68744b7a5
Create Date: 2025-02-10 23:22:32.225980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '460f79c9733b'
down_revision: Union[str, None] = 'a7c68744b7a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('token', sa.String(), nullable=False))
    op.create_unique_constraint('uq_courses_token', 'courses', ['token'])
    op.create_unique_constraint(None, 'courses', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='unique')
    op.drop_constraint('uq_courses_token', 'courses', type_='unique')
    op.drop_column('courses', 'token')
    # ### end Alembic commands ###
