"""Add models for grade configs

Revision ID: 547f621ab82f
Revises: 428bcd9f5db6
Create Date: 2025-07-30 16:14:18.490908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import manytask


# revision identifiers, used by Alembic.
revision: str = '547f621ab82f'
down_revision: Union[str, None] = '428bcd9f5db6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complex_formulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), server_default='0', nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_complex_formulas_course_id_courses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complex_formulas'))
    )
    op.create_table('primary_formulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complex_id', sa.Integer(), nullable=False),
    sa.Column('primary_formula', manytask.models.StrIntFloatDict(), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['complex_id'], ['complex_formulas.id'], name=op.f('fk_primary_formulas_complex_id_complex_formulas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_primary_formulas'))
    )
    op.add_column('tasks', sa.Column('min_score', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'min_score')
    op.drop_table('primary_formulas')
    op.drop_table('complex_formulas')
    # ### end Alembic commands ###
