"""Store RMS ID in User table

Revision ID: 5a4c2adf497b
Revises: 428bcd9f5db6
Create Date: 2025-07-30 08:01:55.198041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a4c2adf497b'
down_revision: Union[str, None] = '428bcd9f5db6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rms_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(op.f('uq_users_rms_id'), 'users', ['rms_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rms_id')
    # ### end Alembic commands ###
