"""Remove 'repo_name' from UserOnCourse

Revision ID: 809847a9ac17
Revises: 322d380606c2
Create Date: 2025-08-04 18:23:28.272252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '809847a9ac17'
down_revision: Union[str, None] = '322d380606c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_on_courses', 'repo_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_on_courses', sa.Column('repo_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
