"""Add Namespace and UserOnNamespace models

Revision ID: 837ef6b0265c
Revises: 2226e9ac60f3
Create Date: 2025-10-06 13:37:00.674144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '837ef6b0265c'
down_revision: Union[str, None] = '2226e9ac60f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('namespaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('gitlab_group_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_namespaces_created_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_namespaces')),
    sa.UniqueConstraint('gitlab_group_id', name=op.f('uq_namespaces_gitlab_group_id')),
    sa.UniqueConstraint('slug', name=op.f('uq_namespaces_slug'))
    )
    op.create_table('users_on_namespaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('namespace_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('NAMESPACE_ADMIN', 'TEACHER', 'PROGRAM_MANAGER', name='user_on_namespace_role', native_enum=False), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], name=op.f('fk_users_on_namespaces_assigned_by_id_users')),
    sa.ForeignKeyConstraint(['namespace_id'], ['namespaces.id'], name=op.f('fk_users_on_namespaces_namespace_id_namespaces')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_users_on_namespaces_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users_on_namespaces')),
    sa.UniqueConstraint('user_id', 'namespace_id', name='_user_namespace_uc')
    )
    op.add_column('courses', sa.Column('namespace_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_courses_namespace_id_namespaces'), 'courses', 'namespaces', ['namespace_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_courses_namespace_id_namespaces'), 'courses', type_='foreignkey')
    op.drop_column('courses', 'namespace_id')
    op.drop_table('users_on_namespaces')
    op.drop_table('namespaces')
    # ### end Alembic commands ###
