"""bonus column for course table

Revision ID: 8bb9753b2425
Revises: 2226e9ac60f3
Create Date: 2025-09-08 17:34:49.511803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bb9753b2425'
down_revision: Union[str, None] = '2226e9ac60f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_on_courses', sa.Column('bonus_score', sa.Integer(), nullable=False, server_default='0', default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_on_courses', 'bonus_score')
    # ### end Alembic commands ###
