"""Add first_name and last_name to User

Revision ID: a0ffb4e05cb1
Revises: 49870528e70a
Create Date: 2025-06-24 12:55:19.636060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'a0ffb4e05cb1'
down_revision: Union[str, None] = '49870528e70a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_on_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('repo_name', sa.String(), nullable=False),
    sa.Column('join_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_course_admin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_users_on_courses_course_id_courses')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_users_on_courses_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users_on_courses')),
    sa.UniqueConstraint('user_id', 'course_id', name='_user_course_uc')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_bonus', sa.Boolean(), nullable=False),
    sa.Column('is_large', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_special', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['task_groups.id'], name=op.f('fk_tasks_group_id_task_groups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_on_course_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('last_submit_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_grades_task_id_tasks')),
    sa.ForeignKeyConstraint(['user_on_course_id'], ['users_on_courses.id'], name=op.f('fk_grades_user_on_course_id_users_on_courses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grades')),
    sa.UniqueConstraint('user_on_course_id', 'task_id', name='_user_on_course_task_uc')
    )
    op.add_column('courses', sa.Column('token', sa.String(), nullable=False))
    op.add_column('courses', sa.Column('is_ready', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('courses', sa.Column('gitlab_course_group', sa.String(), nullable=False))
    op.add_column('courses', sa.Column('gitlab_course_public_repo', sa.String(), nullable=False))
    op.add_column('courses', sa.Column('gitlab_course_students_group', sa.String(), nullable=False))
    op.add_column('courses', sa.Column('gitlab_default_branch', sa.String(), nullable=False))
    op.add_column('courses', sa.Column('task_url_template', sa.String(), nullable=False))
    op.add_column('courses', sa.Column('links', manytask.models.StrStrDict(), server_default='{}', nullable=False))
    op.add_column('courses', sa.Column('timezone', sa.String(), server_default='UTC', nullable=False))
    op.add_column('courses', sa.Column('max_submissions', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('submission_penalty', sa.Float(), server_default='0', nullable=False))
    op.create_unique_constraint(op.f('uq_courses_token'), 'courses', ['token'])
    op.add_column('deadlines', sa.Column('start', sa.DateTime(timezone=True), server_default='2000-01-01 00:00:00+00:00', nullable=False))
    op.add_column('deadlines', sa.Column('steps', manytask.models.FloatDatetimeDict(), server_default='{}', nullable=False))
    op.add_column('deadlines', sa.Column('end', sa.DateTime(timezone=True), server_default='3000-01-01 00:00:00+00:00', nullable=False))
    op.drop_column('deadlines', 'data')
    op.add_column('task_groups', sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('task_groups', sa.Column('position', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('task_groups', 'position')
    op.drop_column('task_groups', 'enabled')
    op.add_column('deadlines', sa.Column('data', sqlite.JSON(), nullable=False))
    op.drop_column('deadlines', 'end')
    op.drop_column('deadlines', 'steps')
    op.drop_column('deadlines', 'start')
    op.drop_constraint(op.f('uq_courses_token'), 'courses', type_='unique')
    op.drop_column('courses', 'submission_penalty')
    op.drop_column('courses', 'max_submissions')
    op.drop_column('courses', 'timezone')
    op.drop_column('courses', 'links')
    op.drop_column('courses', 'task_url_template')
    op.drop_column('courses', 'gitlab_default_branch')
    op.drop_column('courses', 'gitlab_course_students_group')
    op.drop_column('courses', 'gitlab_course_public_repo')
    op.drop_column('courses', 'gitlab_course_group')
    op.drop_column('courses', 'is_ready')
    op.drop_column('courses', 'token')
    op.drop_table('grades')
    op.drop_table('tasks')
    op.drop_table('users_on_courses')
    # ### end Alembic commands ###
