"""Add gitlab, is_ready and ui params to Course

Revision ID: b608e9f744f4
Revises: c3c1bd781e0f
Create Date: 2025-04-25 09:29:45.693247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import manytask


# revision identifiers, used by Alembic.
revision: str = 'b608e9f744f4'
down_revision: Union[str, None] = 'c3c1bd781e0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('is_ready', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('courses', sa.Column('gitlab_course_group', sa.String(), nullable=False))
    op.add_column('courses', sa.Column('gitlab_course_public_repo', sa.String(), nullable=False))
    op.add_column('courses', sa.Column('gitlab_course_students_group', sa.String(), nullable=False))
    op.add_column('courses', sa.Column('gitlab_default_branch', sa.String(), nullable=False))
    op.add_column('courses', sa.Column('task_url_template', sa.String(), nullable=False))
    op.add_column('courses', sa.Column('links', manytask.models.StrStrDict(), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'links')
    op.drop_column('courses', 'task_url_template')
    op.drop_column('courses', 'gitlab_default_branch')
    op.drop_column('courses', 'gitlab_course_students_group')
    op.drop_column('courses', 'gitlab_course_public_repo')
    op.drop_column('courses', 'gitlab_course_group')
    op.drop_column('courses', 'is_ready')
    # ### end Alembic commands ###
