"""Add token

Revision ID: bcca2f4efa74
Revises: a7c68744b7a5
Create Date: 2025-02-14 21:51:23.543046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcca2f4efa74'
down_revision: Union[str, None] = 'a7c68744b7a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('token', sa.String(), nullable=False))
    op.create_unique_constraint(op.f('uq_courses_token'), 'courses', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_courses_token'), 'courses', type_='unique')
    op.drop_column('courses', 'token')
    # ### end Alembic commands ###
