"""Add is_ready to Course

Revision ID: d6f471ccc894
Revises: 0ec2a815ec09
Create Date: 2025-04-04 07:24:39.067041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6f471ccc894'
down_revision: Union[str, None] = '0ec2a815ec09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('is_ready', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'is_ready')
    # ### end Alembic commands ###
