"""Do not save gitlab instance host for users and courses

Revision ID: d8b7ebab0173
Revises: 6a00bd023ee8
Create Date: 2025-06-30 16:02:08.206716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8b7ebab0173'
down_revision: Union[str, None] = '6a00bd023ee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'gitlab_instance_host')
    op.drop_constraint(op.f('_username_gitlab_instance_uc'), 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_username'), 'users', ['username'])
    op.drop_column('users', 'gitlab_instance_host')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gitlab_instance_host', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('uq_users_username'), 'users', type_='unique')
    op.create_unique_constraint(op.f('_username_gitlab_instance_uc'), 'users', ['username', 'gitlab_instance_host'])
    op.add_column('courses', sa.Column('gitlab_instance_host', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
