"""add_description_to_namespace

Revision ID: da0f17b74267
Revises: 837ef6b0265c
Create Date: 2025-10-27 17:25:05.979158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da0f17b74267'
down_revision: Union[str, None] = '837ef6b0265c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('namespaces', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('namespaces', 'description')
    # ### end Alembic commands ###
