"""Added standings settings

Revision ID: daefb685bb83
Revises: 8a711d509af1
Create Date: 2025-10-26 20:49:59.672777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'daefb685bb83'
down_revision: Union[str, None] = '8a711d509af1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('standings_columns', postgresql.ARRAY(sa.Enum('USERNAME', 'FIRST_NAME', 'LAST_NAME', 'GRADE', 'TOTAL_SCORE', 'PERCENT', 'LARGE_COUNT', 'BONUS', 'COMMENT', name='standings_column', native_enum=False)), nullable=False))
    op.add_column('courses', sa.Column('standings_sticky_columns', sa.Integer(), server_default='9', nullable=False))
    op.add_column('courses', sa.Column('standings_reverse_hw_order', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'standings_reverse_hw_order')
    op.drop_column('courses', 'standings_sticky_columns')
    op.drop_column('courses', 'standings_columns')
    # ### end Alembic commands ###
