"""Add is_solved to grade

Revision ID: e3734758a52e
Revises: 837ef6b0265c
Create Date: 2025-10-30 19:33:41.416442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3734758a52e'
down_revision: Union[str, None] = '837ef6b0265c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('is_solved', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grades', 'is_solved')
    # ### end Alembic commands ###
