"""Change RMS ID to string

Revision ID: f1a2b3c4d5e6
Revises: e3734758a52e
Create Date: 2026-02-26 15:17:15.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f1a2b3c4d5e6"
down_revision: Union[str, None] = "e3734758a52e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Для PostgreSQL нужно использовать другой подход
    # Добавляем временный столбец
    op.add_column("users", sa.Column("rms_id_temp", sa.String(), nullable=True))

    # Копируем данные из старого столбца в новый (игнорируем NULL значения)
    op.execute("UPDATE users SET rms_id_temp = CAST(rms_id AS TEXT) WHERE rms_id IS NOT NULL")

    # Заполняем NULL значениями по умолчанию (для строк используем уникальные значения)
    op.execute("UPDATE users SET rms_id_temp = 'null_' || id WHERE rms_id IS NULL")

    # Удаляем старый столбец
    op.drop_column("users", "rms_id")

    # Переименовываем временный столбец
    op.alter_column("users", "rms_id_temp", new_column_name="rms_id")

    # Делаем столбец уникальным и не null
    op.create_unique_constraint(op.f("uq_users_rms_id"), "users", ["rms_id"])
    op.alter_column("users", "rms_id", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем временный столбец
    op.add_column("users", sa.Column("rms_id_temp", sa.Integer(), nullable=True))

    # Копируем данные из старого столбца в новый (только числовые значения)
    op.execute(
        "UPDATE users SET rms_id_temp = CAST(rms_id AS INTEGER) WHERE rms_id ~ '^[0-9]+$' AND rms_id IS NOT NULL"
    )

    # Заполняем NULL значениями по умолчанию
    op.execute("UPDATE users SET rms_id_temp = -1 WHERE rms_id_temp IS NULL")

    # Удаляем старый столбец
    op.drop_column("users", "rms_id")

    # Переименовываем временный столбец
    op.alter_column("users", "rms_id_temp", new_column_name="rms_id")

    # Делаем столбец уникальным и не null
    op.create_unique_constraint(op.f("uq_users_rms_id"), "users", ["rms_id"])
    op.alter_column("users", "rms_id", nullable=False)
    # ### end Alembic commands ###
