services:

    manytask:
        build:
            context: ..
            dockerfile: Dockerfile
            target: app
        container_name: test-manytask
        network_mode: bridge
        env_file: ../.env.sourcecraft
        environment:
            VIRTUAL_HOST: localhost
            VIRTUAL_PORT: 5050
            LETSENCRYPT_HOST: localhost
        ports:
            - "8081:5050"
        volumes:
            - ../manytask:/app/manytask
            - ../.tmp/cache:/cache
        links:
            - postgres:postgres

    postgres:
        image: postgres:17
        container_name: manytask_postgres
        network_mode: bridge
        env_file: ../.env.sourcecraft
        expose:
            - "5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ../scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
            interval: 5s
            timeout: 5s
            retries: 5


volumes:
    postgres_data:
        name: manytask_postgres_data
