name: Build landing and docs and deploy to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build
        uses: diplodoc-platform/docs-build-action@v3
        with:
          src-root: './docs'
          build-root: './build'
          lint-root: './html'
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
