name: Release Drafter


on:
  push:
    branches:
      - main


permissions:
  contents: write


concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true


jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
