name: 'Reusable Build and Push Docker Image'

on:
  workflow_call:
    inputs:
      dockerfile:
        required: false
        default: 'Dockerfile'
        type: string
      target:
        required: false
        default: ''
        type: string
      context:
        required: false
        default: '.'
        type: string
      registry:
        required: false
        default: 'docker.io'
        type: string
      tags:
        required: true
        type: string
      labels:
        required: false
        default: ''
        type: string
      platforms:
        required: false
        default: 'linux/amd64'  # linux/amd64,linux/arm64,linux/arm/v7
        type: string
      push:
        required: false
        default: true
        type: boolean

    secrets:
      registry_username:
        required: false
      registry_password:
        required: false


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      if: ${{ inputs.push }}
      with:
        registry: ${{ inputs.registry }}
        username: ${{ secrets.registry_username }}
        password: ${{ secrets.registry_password }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        target: ${{ inputs.target }}
        push: ${{ inputs.push }}
        tags: ${{ inputs.tags }}
        labels: ${{ inputs.labels }}
        platforms: ${{ inputs.platforms }}
        # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#cache-backend-api
        cache-from: type=gha
        cache-to: type=gha,mode=max
