name: Auto Assign Team Reviewers

on:
  pull_request:
    types: [opened, ready_for_review]

permissions:
  pull-requests: write

jobs:
  assign-team:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Team Reviewers
        env:
          # Create a fine-grained personal access token: https://github.com/settings/personal-access-tokens/new
          # Resource owner: manytask
          # Expiration: whatever you need
          # Repository access : Only select repositories : manytask
          # Under "Repository permissions":
          # "Pull requests" → "Read and write" (to assign reviewers to PRs)
          # "Metadata" → "Read-only" (this is automatically selected)
          # Under "Organization permissions":
          # "Members" → "Read-only" (to read team information)
          #
          # Then, copy the token and add it as a repository secret with name "TEAM_PAT"
          GH_TOKEN: ${{ secrets.TEAM_PAT }}
          TEAM_SLUG: 'dev'
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          # Validate token
          RESPONSE=$(curl -s -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -w "\n%{http_code}" \
            "https://api.github.com/user")
          
          if [ "$(echo "$RESPONSE" | tail -n1)" != "200" ]; then
            exit 1
          fi
          
          # Assign reviewers
          RESPONSE=$(curl -s -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -w "\n%{http_code}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/requested_reviewers" \
            -d "{\"team_reviewers\":[\"$TEAM_SLUG\"]}")
          
          if [ "$(echo "$RESPONSE" | tail -n1)" != "201" ]; then
            exit 1
          fi